---
kind: pipeline
name: lint

clone:
  depth: 100

steps:
- name: flake8
  image: python:3.7
  commands:
  - pip install -r requirements-lint.txt
  - flake8
- name: sdist
  image: python:3.7
  commands:
  - pip install -r requirements-lint.txt
  - ./setup.py sdist
  - twine check dist/*
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]

---
kind: pipeline
name: docs

clone:
  depth: 100

steps:
- name: docs
  image: python:3.7
  commands:
  - apt update
  - apt install -y graphviz
  - pip install -r docs/requirements.txt
  - make -C docs html SPHINXOPTS='-n -W -a'
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
---
kind: pipeline
name: tests

clone:
  depth: 100

services:
- name: database
  image: postgres:11-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: weblate

steps:
- name: test
  image: python:3.5
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    DJANGO_SETTINGS_MODULE: weblate.settings_test
    CI_DATABASE: postgresql
    CI_DB_HOST: database
  commands:
  - apt update
  - apt install -y git-svn  libcairo-dev gir1.2-pango-1.0 libgirepository1.0-dev libenchant1c2a g++ libtesseract-dev libleptonica-dev tesseract-ocr-eng gettext locales
  - pip install  psycopg2-binary
  - pip install -r requirements-optional.txt -r requirements-test.txt -r docs/requirements.txt
  - ./ci/run-test
- name: codecov
  image: robertstettner/drone-codecov
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
---
kind: pipeline
name: migrations:postges

clone:
  depth: 100

services:
- name: database
  image: postgres:11-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: weblate
    CI_DATABASE: postgresql

steps:
- name: test
  image: python:3.5
  environment:
    LANG: C
    LC_ALL: C
    DJANGO_SETTINGS_MODULE: weblate.settings_test
    CI_DATABASE: postgresql
    CI_DB_HOST: database
  commands:
  - apt update
  - apt install -y git-svn libcairo-dev gir1.2-pango-1.0 libgirepository1.0-dev libenchant1c2a g++ libtesseract-dev libleptonica-dev tesseract-ocr-eng gettext locales postgresql-client
  - pip install 'Django>=2.1,<2.2' psycopg2-binary==2.7.7
  - pip install -r requirements-optional.txt -r requirements-test.txt -r docs/requirements.txt
  - ./ci/run-migrate
- name: codecov
  image: robertstettner/drone-codecov
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
---
kind: pipeline
name: migrations:mariadb

clone:
  depth: 100

services:
- name: database
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: weblate

steps:
- name: test
  image: python:3.5
  environment:
    LANG: C
    LC_ALL: C
    DJANGO_SETTINGS_MODULE: weblate.settings_test
    CI_DATABASE: mysql
    CI_DB_HOST: database
  commands:
  - apt update
  - apt install -y git-svn libcairo-dev gir1.2-pango-1.0 libgirepository1.0-dev libenchant1c2a g++ libtesseract-dev libleptonica-dev tesseract-ocr-eng gettext locales default-mysql-client
  - pip install 'Django>=2.1,<2.2' mysqlclient
  - pip install -r requirements-optional.txt -r requirements-test.txt -r docs/requirements.txt
  - ./ci/run-migrate
- name: codecov
  image: robertstettner/drone-codecov
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
...
