---
kind: pipeline
name: lint

clone:
  depth: 100

steps:
- name: flake8
  image: weblate/cidocker:3.7
  commands:
  - pip install -r requirements-lint.txt
  - flake8
- name: sdist
  image: weblate/cidocker:3.7
  commands:
  - pip install -r requirements-lint.txt
  - ./setup.py sdist
  - twine check dist/*
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]

---
kind: pipeline
name: docs

clone:
  depth: 100

steps:
- name: docs
  image: weblate/cidocker:3.7
  commands:
  - pip install -r docs/requirements.txt
  - make -C docs html SPHINXOPTS='-n -W -a'
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
---
kind: pipeline
name: tests:selenium

clone:
  depth: 100

services:
- name: database
  image: postgres:11-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: weblate
- name: sauce
  image: nijel/sauce-connect:latest
  environment:
    SAUCE_USERNAME:
      from_secret: SAUCE_USERNAME
    SAUCE_ACCESS_KEY:
      from_secret: SAUCE_ACCESS_KEY

steps:
- name: test
  image: weblate/cidocker:3.7
  ports:
  - 9090
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    DJANGO_SETTINGS_MODULE: weblate.settings_test
    CI_DATABASE: postgresql
    CI_DB_HOST: database
    SAUCE_USERNAME:
      from_secret: SAUCE_USERNAME
    SAUCE_ACCESS_KEY:
      from_secret: SAUCE_ACCESS_KEY
  commands:
  - apt update
  - apt install -y daemon
  - pip install  psycopg2-binary
  - pip install -r requirements-optional.txt -r requirements-test.txt -r docs/requirements.txt
  - ./ci/run-selenium
- name: codecov
  image: weblate/cidocker:3.7
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    CI: drone
  commands:
  - export CI=drone
  - codecov
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
---
kind: pipeline
name: tests:python-2.7

clone:
  depth: 100

services:
- name: database
  image: postgres:11-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: weblate

steps:
- name: test
  image: weblate/cidocker:2.7
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    DJANGO_SETTINGS_MODULE: weblate.settings_test
    CI_DATABASE: postgresql
    CI_DB_HOST: database
  commands:
  - pip install  psycopg2-binary==2.7.7
  - pip install -r requirements-optional.txt -r requirements-test.txt -r docs/requirements.txt
  - ./ci/run-test
- name: codecov
  image: weblate/cidocker:2.7
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    CI: drone
  commands:
  - export CI=drone
  - codecov
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
---
kind: pipeline
name: tests:python-3.7

clone:
  depth: 100

services:
- name: database
  image: postgres:11-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: weblate

steps:
- name: test
  image: weblate/cidocker:3.7
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    DJANGO_SETTINGS_MODULE: weblate.settings_test
    CI_DATABASE: postgresql
    CI_DB_HOST: database
  commands:
  - pip install  psycopg2-binary
  - pip install -r requirements-optional.txt -r requirements-test.txt -r docs/requirements.txt
  - ./ci/run-test
- name: codecov
  image: weblate/cidocker:3.7
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    CI: drone
  commands:
  - export CI=drone
  - codecov
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
---
kind: pipeline
name: migrations

clone:
  depth: 100

services:
- name: database
  image: postgres:11-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: weblate
    CI_DATABASE: postgresql

steps:
- name: test
  image: weblate/cidocker:3.7
  environment:
    LANG: C
    LC_ALL: C
    DJANGO_SETTINGS_MODULE: weblate.settings_test
    CI_DATABASE: postgresql
    CI_DB_HOST: database
  commands:
  - pip install 'Django>=2.1,<2.2' psycopg2-binary==2.7.7
  - pip install -r requirements-optional.txt -r requirements-test.txt -r docs/requirements.txt
  - ./ci/run-migrate
- name: codecov
  image: weblate/cidocker:3.7
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    CI: drone
  commands:
  - export CI=drone
  - codecov
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    username:
      from_secret: SMTP_USER
    password:
      from_secret: SMTP_PASS
    from: noreply+ci@weblate.org
  when:
    status: [ changed, failure ]
...
