linters:
  flake8:
    fixer: true
    python: 3
    config: setup.cfg
  csslint: {  }
  shellcheck:
    shell: bash
  phpcs:
    standard: PSR2
    fixer: true
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'vendor/*'
fixers:
  enable: true
