comment:
  layout: reach, changes, diff, files
coverage:
  ignore:
  - .*/settings_.*.py
  - .*/settings.py
  - .*/wsgi.py
  status:
    project:
      default:
        target: '90'
codecov:
  notify:
    # There are currently 9 builds in the Test GitHub Action
    after_n_builds: 9
