version: '3'

services:
  database:
    # Use older MySQL to avoid hitting https://code.djangoproject.com/ticket/29480
    image: mysql:5.6
    ports:
      - 60000:3306
    environment:
      MYSQL_ROOT_PASSWORD: weblate
